// app/public/output/addressee/modal/text-import/text-import.vue
<template>
	<section>
		<div class="modal-header modal-header-update">
			<div class="modal-title">收信人录入</div>
		</div>
		<div class="main clearfix">
			<form :model="validateForm">
				<a-form-item name="phoneNumber"
					:rules="[{ 'required': true, 'message': '请输入手机号码' }, { 'validator': 'forbiddenCurrTextValidator()' }]">
					<span style="font-size: 15px;color: #ccc;">多个手机号码以英文逗号隔开</span>
					<a-textarea ref="inputElement" v-model:value="validateForm.phoneNumber" rows="5"
						style="margin: 5px 0;"></a-textarea>
				</a-form-item>
				<span :style="{
					color: numbersLength > 1000 ? 'red' : '',
					float: 'right'
				}">当前共{{ numbersLength }}/1000个号码</span>
			</form>
		</div>
		<div class="modal-footer modal-footer-update">
			<icc-button :btn-type="'hollow'" @btnClick="close"><span>取消</span></icc-button>
			<icc-button :btn-type="'default'" :is-disabled="!validateForm.valid" @btnClick="(e) => save(validateForm.value)">
				<span>确定</span></icc-button>
		</div>
	</section>
</template>
<script lang="ts" setup>
import { ref } from "vue";
import { Addressee } from "src/app/routes/message/Addressee";
import { useNotification } from "@icc/hooks";

const dialogService = useNotification();

defineOptions({
	name: 'IccTextImport',
});

const emits = defineEmits(["close"]);
let iconImg1: string = "./assets/images/send/contact-blue.png";
const validateForm = ref<any>();
const numbersLength = ref<number>(0);
const inputElement = ref<any>();

function ngOnInit() {
	validateForm.value = {
		phoneNumber: '',
	};
}
ngOnInit();

function close() {
	emits('close');
}

function save(form) {
	let value: string = form.phoneNumber;
	let phoneNumber = value.split(',').filter(str => str !== '');
	if (phoneNumber.length > 0) {
		phoneNumber = phoneNumber.map(str => str.trim());
	}
	// 号码验证
	const exp = /^[1][0-9]{10}$/;
	// 整体文本验证，逗号之间不能为空
	const textExp = /^([1][0-9]{10},?)+$/;
	// 不符合手机号码的格式，弹出提示
	if (!textExp.test(value) || !phoneNumber.some(item => exp.test(item))) {
		dialogService.error('收信人录入', '请按要求格式录入手机号！');
		return;
	}
	let temp = new Addressee();
	temp.name = '收信人';
	temp.icon = iconImg1;
	temp.id = new Date().getTime();
	temp.contacts = phoneNumber.map(num => "," + num);
	temp.len = phoneNumber.length;
	emits('close', temp);
}

function forbiddenCurrTextValidator(): any {
	return (control: any): any | null => {
		const exp = /^[,0-9]*$/
		const val = control.value;
		if (val !== '' && !exp.test(val)) {
			return { validate: true };
		}
		const dotExp = new RegExp('[,]+', 'g');
		let formatString = val.trim().replace(dotExp, ',');
		let numbers = formatString.split(',').filter(str => str !== '');
		numbersLength.value = numbers.length;
		if (numbersLength.value > 1000) {
			return { length: true };
		}
		return null;

	};
}
</script>
<style lang="less" scoped>
.mockTextarea {
	display: inline-block;
	overflow-x: hidden;
	overflow-y: auto;
	flex-direction: column;
	// margin: 20px 0;
	padding: 8px 10px;
	border: 1px solid #d9d9d9;
	border-width: 1px;
	border-style: solid;
	border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));
	border-radius: 4px;
	border-image: initial;
	width: 100%;
	max-width: 100%;
	height: 150px;
	min-height: 150px;
	appearance: textarea;
	background-color: -internal-light-dark(rgb(255, 255, 255), rgb(59, 59, 59));
	resize: auto;
	cursor: text;
	vertical-align: middle;
	text-overflow: ellipsis;
	text-align: start;
	text-indent: 0;
	text-shadow: none;
	text-transform: none;
	font: 400 13.3333px Arial;
	color: #49536e;
	overflow-wrap: break-word;
	word-break: break-all;
	word-spacing: normal;
	letter-spacing: normal;
	white-space: pre-wrap;
	transition: all .3s, height 0s;

	-webkit-transition: all .3s, height 0s;
	scrollbar-color: rgba(0, 0, 0, .3) #6e6e6e;
	scrollbar-width: thin;
	text-rendering: auto;
	-webkit-rtl-ordering: logical;

	&:hover {
		border-color: #40a9ff !important;
	}

	&:focus {
		outline: none;
		box-shadow: 0 0 5px rgba(222, 240, 255, .8);

		-webkit-box-shadow-color: #1890ff;
	}

	&:focus:before {
		content: none;
	}

	&:empty:before {
		padding-top: 10px;
		line-height: 21px;
		vertical-align: middle;
		font-size: 14px;
		color: #ccc;
		content: attr(placeholder);
	}

	.innerPaster {
		display: inline-block;
		// margin: 0 5px;
		// padding: 0 5px;
		border: 1px solid #b8e5f5;
		width: auto;
		height: 21px;
		background: rgba(184, 229, 245, .14);
	}

	.innerShortLink {
		display: inline-block;
		// margin: 0 5px;
		// padding: 0 5px;
		border: 1px solid #b8e5f5;
		width: auto;
		height: 21px;
		background: rgba(184, 229, 245, .14);
	}
}
</style>

// app/public/examples/addressee/modal/text-import/text-import.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, OnInit, OnChanges, SimpleChanges, ChangeDetectorRef, ElementRef } from '@angular/core';
import { AbstractControl, UntypedFormBuilder, FormControl, UntypedFormGroup, ValidationErrors, ValidatorFn, Validators } from '@angular/forms';
import { format } from '@delon/util';
import { DialogService } from '@icc/common-lib';
import { NzModalRef } from 'ng-zorro-antd/modal';
import { Addressee } from 'src/app/routes/message/Addressee';

@Component({
  selector: 'icc-text-import',
  templateUrl: './text-import.component.html',
  styleUrls: ['./text-import.component.less'],
})
export class TextImportModalComponent implements OnInit {
  constructor(private cdr: ChangeDetectorRef, private modal: NzModalRef, private fb: UntypedFormBuilder, private dialogService: DialogService) {}

  validateForm: UntypedFormGroup;

  // 号码个数
  numbersLength: number = 0;

  iconImg1 = "./assets/images/send/contact-blue.png";

  @ViewChild('inputElement', { static: false }) inputElement: ElementRef;

  ngOnInit(): void {
    this.validateForm = this.fb.group({
      phoneNumber: ['', [Validators.required, this.forbiddenCurrTextValidator()]],
    });
  }

  forbiddenCurrTextValidator(): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      const exp = /^[,0-9]*$/
      const val = control.value;
      if (val !== '' && !exp.test(val)) {
        return { validate : true };
      }
      const dotExp = new RegExp('[,]+', 'g');
      let formatString = val.trim().replace(dotExp, ',');
      let numbers = formatString.split(',').filter(str => str !== '');
      this.numbersLength = numbers.length;
      if (this.numbersLength > 1000) {
        return { length : true };
      }
      return null;
      
    };
  }

  save(form) {
    let value: string = form.phoneNumber;
    let phoneNumber = value.split(',').filter(str => str !== '');
    if (phoneNumber.length > 0) {
      phoneNumber = phoneNumber.map(str => str.trim());
    }
    // 号码验证
    const exp = /^[1][0-9]{10}$/;
    // 整体文本验证，逗号之间不能为空
    const textExp = /^([1][0-9]{10},?)+$/;
    // 不符合手机号码的格式，弹出提示
    if ( !textExp.test(value) || !phoneNumber.some(item => exp.test(item))) {
      this.dialogService.notification.error('收信人录入', '请按要求格式录入手机号！');
      return;
    }
    let temp = new Addressee();
    temp.name = '收信人';
    temp.icon = this.iconImg1;
    temp.id = new Date().getTime();
    temp.contacts = phoneNumber.map(num => "," + num);
    temp.len = phoneNumber.length;
    this.modal.close(temp);
  }

  close() {
    this.modal.destroy();
  }
}

<!-- HTML contenteditable  by：LHD    -->
<div class="modal-header modal-header-update">
  <div class="modal-title">收信人录入</div>
</div>
<div class="main clearfix">
  <form nz-form [formGroup]="validateForm">
    <nz-form-item>
      <nz-form-control [nzErrorTip]="currErrorTpl">
        <span style="font-size: 15px;color: #ccc;">多个手机号码以英文逗号隔开</span>
        <textarea #inputElement formControlName="phoneNumber" rows="5" style="margin: 5px 0;" nz-input></textarea>
          <ng-template #currErrorTpl let-control>
            <ng-container *ngIf="control.hasError('required')">
              请输入手机号码
            </ng-container>
            <ng-container *ngIf="control.hasError('validate')">
              仅允许录入数字及英文逗号分隔符
            </ng-container>
            <ng-container *ngIf="control.hasError('length')">
              仅允许录入1000个以内手机号！
            </ng-container>
          </ng-template>
      </nz-form-control>
    </nz-form-item>
    <span [ngStyle]="{
      color: numbersLength > 1000 ? 'red' : '',
      float: 'right'
      }">当前共{{numbersLength}}/1000个号码</span>
  </form>
</div>
<div class="modal-footer modal-footer-update">
  <icc-button [btnType]="'hollow'" (btnClick)="close()"><span>取消</span></icc-button>
  <icc-button [btnType]="'default'" [isDisabled]="!validateForm.valid"  (btnClick)="save(validateForm.value)">
    <span>确定</span></icc-button>
</div>
