// app/public/examples/file-upload/file-upload.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { UploadFilter } from "ng-zorro-antd/upload";

@Component({
  selector: "file-upload",
  templateUrl: "./file-upload.component.html",
  styleUrls: ["./file-upload.component.less"],
})
/* 该组件以antd中的nz-upload为基础，其中的参数请详见 https://ng.ant.design/components/upload/zh */
export class FileUploadComponent implements OnInit {
  /*------------upload参数---------------*/
  // 接受上传的文件类型
  @Input() accept: string;
  // 必选参数, 上传的地址
  @Input() action: string;
  // 上传文件之前的钩子，参数为上传的文件，若返回 false 则停止上传。注意：IE9 不支持该方法；注意：务必使用 => 定义处理方法。
  @Input() beforeUpload: Function;
  // 通过覆盖默认的上传行为，可以自定义自己的上传实现；注意：务必使用 => 定义处理方法。
  @Input() customRequest: Function;
  // 是否禁用
  @Input() disabled = false;
  // 限制文件大小，单位：KB；0 表示不限
  @Input() size = 0;
  // 限制文件类型，例如：image/png,image/jpeg,image/gif,image/bmp
  @Input() fileType: string;
  // 自定义过滤器
  @Input() filter: UploadFilter[];
  // 上传请求时是否携带 cookie
  @Input() withCredentials = false;
  // 上传文件改变时触发
  @Output() handleChange: EventEmitter<any> = new EventEmitter<any>();
  /*--------------nz-progress参数-------------------*/
  // 百分比
  @Input() percent = 0;
  // 进度条状态（枚举）'success' | 'exception' | 'active' | 'normal'
  @Input() status: string;

  /*--------------自定义参数-------------------*/
  // 模板路径
  @Input() exampleUrl: string;
  // 是否显示进度条：请在上传请求开始时设置为true,在请求结束（成功或失败）之后设置为false
  @Input() hasProgress = false;
  // 删除导入的文件
  @Output() remove: EventEmitter<any> = new EventEmitter<any>();
  // 导入总条目数
  @Input() totalCount = 0;
  // 符合规范的条目数
  @Input() successCount = 0;
  // 上传失败原因
  @Input() logUrl: string;
  // 文件列表，双向绑定，该数组用于自定义列表显示，并不沿用nz-upload的封装
  fileList: Array<any> = [];
  // 所选文件名
  currentFileName = "";
  // 文件上传状态
  fileStatusObj = {
    "0": "uploading",
    "1": "done",
    "2": "error",
  };

  // 针对非常规的假上传行为，控制显示原因（情况：员工/客户通讯录的上传）
  @Input() showReason = true;

  // 验证失败
  @Input() errorMsg: string;
  constructor() {}

  fileTypeSelection = {
    fileType: 1,
    fileList: [
      {
        index: 1,
        name: "xls/xlsx",
        value: ".xls",
      },
      {
        index: 3,
        name: "txt",
        value: ".txt",
      },
    ],
  };

  separatorSelection = {
    value: 4,
    list: [
      // {
      //   index: 2,
      //   name: '空格',
      //   value: ' ',
      // },
      // {
      //   index: 3,
      //   name: 'tab',
      //   value: '\t',
      // },
      {
        index: 4,
        name: "|",
        value: "|",
      },
      {
        index: 1,
        name: "逗号(英文)",
        value: ",",
      },
    ],
  };

  hasDeleteIcon = false;

  ngOnInit() {}

  getSelectedFileSuff() {
    let suff;
    this.fileTypeSelection.fileList.forEach(item => {
      if (this.fileTypeSelection.fileType === item.index) {
        suff = item.name;
      }
    });
    return suff;
  }

  getSeparatorIndex() {
    let index;
    if (this.fileTypeSelection.fileType === 3) {
      index = this.separatorSelection.value;
    } else {
      index = -1;
    }
    return index;
  }

  changeFileType(evt: any) {
    this.removeFile(0, undefined);
  }

  /*选中文件触发该事件*/
  change(evt) {
    this.removeFile(0, "change");
    this.percent = 0;
    if (evt && (evt.type === "success" || evt.type === "error")) {
      this.hasDeleteIcon = true;
    } else {
      this.hasDeleteIcon = false;
    }
    this.status = "normal";
    this.fileList = [evt.file];
    this.currentFileName = evt.file.name;
    this.handleChange.emit(evt);
  }
  /*删除上传的文件触发该事件*/
  removeFile(index, type?) {
    const file: any = this.fileList.splice(index, 1)[0];
    this.currentFileName = "";
    if (!type || (type && type !== "change")) {
      this.remove.emit(file);
    }
  }
  reset() {
    this.fileList = [];
    this.currentFileName = "";
    this.percent = 0;
    this.status = "normal";
    this.logUrl = "";
  }
}

<div class="icc-upload">
  <!--文字提示区-->
  <nz-alert nzType="warning" nzCloseable="false" [nzMessage]="warnMessage" style="margin: 0 -25px 20px -25px">
    <ng-template #warnMessage>
      <ng-content></ng-content>
      <span class="warning-text">文件不可以超过100M，为确保导入文件格式的正确性，请</span>
      <a [href]="exampleUrl" target="_blank">下载导入模板</a>
    </ng-template>
  </nz-alert>

  <div class="row-item">
    <label class="item-name">文件类型：</label>
    <nz-radio-group [(ngModel)]="fileTypeSelection.fileType" (ngModelChange)="changeFileType($event)">
      <label nz-radio *ngFor="let item of fileTypeSelection.fileList" [nzValue]="item.index" class="radio-item">
        {{ item.name }}
      </label>
    </nz-radio-group>
  </div>

  <div class="row-item" *ngIf="fileTypeSelection.fileType === 3">
    <label class="item-name">分隔符：</label>
    <nz-radio-group [(ngModel)]="separatorSelection.value">
      <label nz-radio *ngFor="let item of separatorSelection.list" [nzValue]="item.index" class="radio-item">
        {{ item.name }}
      </label>
    </nz-radio-group>
  </div>

  <!--附件上传区-->
  <div class="upload-box">
    <nz-input-group nzSize="large" [nzAddOnAfter]="suffixText">
      <input type="text" nz-input class="show-input" [ngModel]="currentFileName" disabled />
    </nz-input-group>
    <ng-template #suffixText>
      <nz-upload
        [nzAccept]="accept"
        [nzAction]="action"
        [nzBeforeUpload]="$any(beforeUpload)"
        [nzCustomRequest]="$any(customRequest)"
        [nzDisabled]="disabled"
        [nzSize]="size"
        [nzFileType]="fileType"
        [nzFilter]="filter"
        [nzShowUploadList]="false"
        [nzWithCredentials]="withCredentials"
        (nzChange)="change($event)"
      >
        选择文件
      </nz-upload>
    </ng-template>
    <p class="limit-size">文件不能超过{{ (size / 1024 / 1024).toFixed(0) }}M</p>
    <ul *ngIf="fileList.length" class="file-list">
      <li *ngFor="let file of fileList; let i = index" class="file-item">
        <label class="left">
          <i *ngIf="fileStatusObj['0'] === file.status" nz-icon nzType="loading" nzTheme="outline"></i>
          <i *ngIf="fileStatusObj['1'] === file.status" nz-icon nzType="file-excel" nzTheme="outline"></i>
          <i *ngIf="fileStatusObj['2'] === file.status" nz-icon nzType="file-excel" nzTheme="outline" style="color: red"></i>
          <span
            [ngStyle]="{
              color: fileStatusObj['2'] === file.status ? 'red' : '#49536e'
            }"
          >
            {{ file.name }}
          </span>
        </label>
        <img class="right" *ngIf="hasDeleteIcon" (click)="removeFile(i)" src="./assets/images/btnIcon/delete_red.png" alt="" />
      </li>
    </ul>
  </div>
  <!--加载进度区-->
  <div class="progress-box" *ngIf="hasProgress">
    <p>
      <span class="float-left">正在导入</span>
      <span class="float-right">{{ percent }}%</span>
    </p>
    <nz-progress [nzShowInfo]="false" [nzStatus]="$any(status)" [nzPercent]="percent"></nz-progress>
  </div>
  <!--附件统计区-->
  <div *ngIf="fileList.length && !hasProgress && showReason">
    <section>
      <div class="notification-wrapper total-box">
        <div class="title">
          <img *ngIf="fileStatusObj['1'] === fileList[0].status" src="./assets/images/layout/success.png" alt="" />
          <img *ngIf="fileStatusObj['2'] === fileList[0].status" src="./assets/images/layout/error.png" alt="" />
          <span *ngIf="fileStatusObj['1'] === fileList[0].status" class="tip-text">导入成功</span>
          <span *ngIf="fileStatusObj['2'] === fileList[0].status" class="tip-text">导入失败</span>
        </div>
        <div class="content">
          <span *ngIf="errorMsg">{{ errorMsg }}</span>
          <span *ngIf="!errorMsg && fileStatusObj['1'] === fileList[0].status && totalCount == successCount">
            共导入{{ totalCount }}条记录！全部数据项符合规范！
          </span>
          <span *ngIf="!errorMsg && fileStatusObj['1'] === fileList[0].status && totalCount != successCount">
            共导入{{ totalCount }}条记录！{{ successCount }}条记录符合规范！部分数据项不符合规范！修改后请重新导入！
          </span>
          <span *ngIf="!errorMsg && fileStatusObj['2'] === fileList[0].status">
            共导入{{ totalCount }}条记录！{{ successCount }}条记录符合规范！部分数据项不符合规范！修改后请重新导入！
          </span>
          <a *ngIf="!errorMsg && logUrl" [href]="logUrl">下载查看原因</a>
        </div>
      </div>
    </section>
  </div>
  <div *ngIf="!fileList.length && !hasProgress && errorMsg">
    <section>
      <div class="notification-wrapper total-box">
        <div class="title">
          <img src="./assets/images/layout/error.png" alt="" />
          <span class="tip-text">导入失败</span>
        </div>
        <div class="content">
          <span *ngIf="errorMsg">{{ errorMsg }}</span>
        </div>
      </div>
    </section>
  </div>
</div>

// app/public/output/file-upload/file-upload.vue
<template>
<div class="icc-upload">
  <a-alert type="warning" closeable="false" style="margin: 0 -25px 20px -25px">
    <template #message>
      <ng-content></ng-content>
      <span class="warning-text">文件不可以超过100M，为确保导入文件格式的正确性，请</span>
      <a :href="exampleUrl" target="_blank">下载导入模板</a>
    </template>
</a-alert>

  <div class="row-item">
    <label class="item-name">文件类型：</label>
    <a-radio-group v-model:value="fileTypeSelection.fileType" @change="changeFileType">
      <a-radio v-for="item in fileTypeSelection.fileList" :value="item.index" class="radio-item">
        {{ item.name }}
      </a-radio>
    </a-radio-group>
  </div>

  <div class="row-item" v-if="fileTypeSelection.fileType === 3">
    <label class="item-name">分隔符：</label>
    <a-radio-group v-model:value="separatorSelection.value">
      <a-radio v-for="item in separatorSelection.list" :value="item.index" class="radio-item">
        {{ item.name }}
      </a-radio>
    </a-radio-group>
  </div>

  <div class="upload-box">
    <a-input-group size="large">
      <a-input type="text" class="show-input" v-model:value="currentFileName" disabled>
<template #addOnAfter>
      <a-upload :accept="accept" :action="action" :before-upload="beforeUpload" :custom-request="customRequest" :disabled="disabled" :show-upload-list="false" :with-credentials="withCredentials" @change="change">
        选择文件
      </a-upload>
    </template>
</a-input>
    </a-input-group>
    <p class="limit-size">文件不能超过{{ (size / 1024 / 1024).toFixed(0) }}M</p>
    <ul v-if="fileList.length" class="file-list">
      <li v-for="(file, i ) in fileList" class="file-item">
        <label class="left">
          <loading-outlined v-if="fileStatusObj['0'] === file.status" />
          <file-excel-outlined v-if="fileStatusObj['1'] === file.status" />
          <file-excel-outlined v-if="fileStatusObj['2'] === file.status" style="color: red" />
          <span :style="{
              color: fileStatusObj['2'] === file.status ? 'red' : '#49536e'
            }">
            {{ file.name }}
          </span>
        </label>
        <img class="right" v-if="hasDeleteIcon" @click="(e) => removeFile(i)" src="./assets/images/btnIcon/delete_red.png" alt="" />
      </li>
    </ul>
  </div>
  <div class="progress-box" v-if="hasProgress">
    <p>
      <span class="float-left">正在导入</span>
      <span class="float-right">{{ percent }}%</span>
    </p>
    <a-progress :show-info="false" :status="status" :percent="percent"></a-progress>
  </div>
  <div v-if="fileList.length && !hasProgress && showReason">
    <section>
      <div class="notification-wrapper total-box">
        <div class="title">
          <img v-if="fileStatusObj['1'] === fileList[0].status" src="./assets/images/layout/success.png" alt="" />
          <img v-if="fileStatusObj['2'] === fileList[0].status" src="./assets/images/layout/error.png" alt="" />
          <span v-if="fileStatusObj['1'] === fileList[0].status" class="tip-text">导入成功</span>
          <span v-if="fileStatusObj['2'] === fileList[0].status" class="tip-text">导入失败</span>
        </div>
        <div class="content">
          <span v-if="errorMsg">{{ errorMsg }}</span>
          <span v-if="!errorMsg && fileStatusObj['1'] === fileList[0].status && totalCount == successCount">
            共导入{{ totalCount }}条记录！全部数据项符合规范！
          </span>
          <span v-if="!errorMsg && fileStatusObj['1'] === fileList[0].status && totalCount != successCount">
            共导入{{ totalCount }}条记录！{{ successCount }}条记录符合规范！部分数据项不符合规范！修改后请重新导入！
          </span>
          <span v-if="!errorMsg && fileStatusObj['2'] === fileList[0].status">
            共导入{{ totalCount }}条记录！{{ successCount }}条记录符合规范！部分数据项不符合规范！修改后请重新导入！
          </span>
          <a v-if="!errorMsg && logUrl" :href="logUrl">下载查看原因</a>
        </div>
      </div>
    </section>
  </div>
  <div v-if="!fileList.length && !hasProgress && errorMsg">
    <section>
      <div class="notification-wrapper total-box">
        <div class="title">
          <img src="./assets/images/layout/error.png" alt="" />
          <span class="tip-text">导入失败</span>
        </div>
        <div class="content">
          <span v-if="errorMsg">{{ errorMsg }}</span>
        </div>
      </div>
    </section>
  </div>
</div>

</template>
<script lang="ts" setup>
import { computed, PropType, reactive, ref } from "vue";

defineOptions({
	name: 'FileUpload',
});

const props = defineProps({
	accept: {
	type: String,
	},
	action: {
	type: String,
	},
	beforeUpload: {
	type: Object as PropType<Function>,
	},
	customRequest: {
	type: Object as PropType<Function>,
	},
	disabled: {
	type: Boolean,
		default: false
	},
	size: {
	type: Number,
		default: 0
	},
	fileType: {
	type: String,
	},
	filter: {
	type: Object as PropType<any[]>,
	},
	withCredentials: {
	type: Boolean,
		default: false
	},
	percent: {
	type: Number,
		default: 0
	},
	status: {
	type: String,
	},
	exampleUrl: {
	type: String,
	},
	hasProgress: {
	type: Boolean,
		default: false
	},
	totalCount: {
	type: Number,
		default: 0
	},
	successCount: {
	type: Number,
		default: 0
	},
	logUrl: {
	type: String,
	},
	showReason: {
	type: Boolean,
		default: true
	},
	errorMsg: {
	type: String,
	},
});
const emits = defineEmits(["handleChange","update:percent","update:status","remove","update:logUrl"]);
const currentFileName = ref<string>("");
const fileList = ref<Array<any>>([]);
const hasDeleteIcon = ref<boolean>(false);
const fileTypeSelection = reactive({
    fileType: 1,
    fileList: [
      {
        index: 1,
        name: "xls/xlsx",
        value: ".xls",
      },
      {
        index: 3,
        name: "txt",
        value: ".txt",
      },
    ],
  });
const separatorSelection = reactive({
    value: 4,
    list: [
      // {
      //   index: 2,
      //   name: '空格',
      //   value: ' ',
      // },
      // {
      //   index: 3,
      //   name: 'tab',
      //   value: '\t',
      // },
      {
        index: 4,
        name: "|",
        value: "|",
      },
      {
        index: 1,
        name: "逗号(英文)",
        value: ",",
      },
    ],
  });
const fileStatusObj = reactive({
    "0": "uploading",
    "1": "done",
    "2": "error",
  });
const percent = computed({
	get() {
		return props.percent;
	},
	set(value) {
		emits('update:percent', value);
	}
});const status = computed({
	get() {
		return props.status;
	},
	set(value) {
		emits('update:status', value);
	}
});const logUrl = computed({
	get() {
		return props.logUrl;
	},
	set(value) {
		emits('update:logUrl', value);
	}
});

function ngOnInit() {}
ngOnInit();

function removeFile(index, type?) {
    const file: any = fileList.value.splice(index, 1)[0];
    currentFileName.value = "";
    if (!type || (type && type !== "change")) {
      emits('remove', file);
    }
  }

function changeFileType(evt: any) {
    removeFile(0, undefined);
  }

function change(evt) {
    removeFile(0, "change");
    percent.value = 0;
    if (evt && (evt.type === "success" || evt.type === "error")) {
      hasDeleteIcon.value = true;
    } else {
      hasDeleteIcon.value = false;
    }
    status.value = "normal";
    fileList.value = [evt.file];
    currentFileName.value = evt.file.name;
    emits('handleChange', evt);
  }
</script>
<style lang="less" scoped>
*{
  :deep(*) {
    .ant-progress-text {
      display: none;
    }
    .ant-progress-outer {
      margin-right: 0 !important;
      padding-right: 0 !important;
    }
    .ant-progress-inner {
      background: rgb(220, 221, 233);
    }
    nz-upload {
      cursor: pointer;
    }
    .warning-text {
      color: rgba(163, 133, 57, 0.85);
    }
    .icc-upload {
      padding: 0 25px;
      .row-item {
        line-height: 38px;
        .item-name {
          display: inline-block;
          width: 70px;
        }
        .radio-item {
          width: 100px;
        }
        .radio-item:nth-of-type(1) {
          margin-left: 10px;
        }
      }
      .upload-box {
        width: 85%;
        margin: 10px 0 20px 0;
        .show-input {
          height: 30px;
          color: #49536e;
          font-size: 14px;
          background: #fff;
        }
      }
      .limit-size {
        margin-top: 8px;
        color: #abb4cf;
        font-size: 12px;
      }
      .file-list {
        margin: 0;
        padding: 0;
        list-style: none;
        .file-item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin: 8px 0;
          padding: 5px;
          border-radius: 2px;
          cursor: pointer;
          &:hover {
            background: rgb(240, 241, 249);
          }
          .left {
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            i {
              margin-right: 10px;
              color: #4880ff;
              font-size: 16px;
            }
          }
          .right {
            cursor: pointer;
          }
        }
      }
      .progress-box {
        margin-bottom: 10px;
        padding: 10px 20px;
        font-size: 12px;
        background: rgb(240, 241, 249);
        border-radius: 2px;
      }
      .float-left {
        float: left;
      }
      .float-right {
        float: right;
      }
      .total-box {
        width: 100%;
        padding: 8px 8px 2px 8px;
        background: rgb(240, 241, 249);
        border-radius: 2px;
        .content {
          padding: 0 0 5px 42px;
        }
      }
    }
  }
}
</style>
